substitutions:
  _CLOUDSDK_COMPUTE_ZONE: asia-northeast1-a
  _CLOUDSDK_CONTAINER_CLUSTER: gek-gitops-cluster

steps:
  - id: 'Deploy the new version of container image'
    name: gcr.io/cloud-builders/kubectl
    args:
      - apply
      - -f
      - kubernetes.yaml
    env:
      - CLOUDSDK_COMPUTE_ZONE=$_CLOUDSDK_COMPUTE_ZONE
      - CLOUDSDK_CONTAINER_CLUSTER=$_CLOUDSDK_CONTAINER_CLUSTER

  ### - GitHub Env repo Access by SSH
  - id: 'access the id_github file from secret manager'
    name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        gcloud secrets versions access latest --secret=id_github > /root/.ssh/id_github
    volumes:
      - name: ssh
        path: /root/.ssh

  - id: 'Set up git with key and domain'
    name: gcr.io/cloud-builders/git
    entrypoint: bash
    args:
      - -c
      - |
        chmod 600 /root/.ssh/id_github
        cat <<EOF >/root/.ssh/config
        Hostname github.com
        IdentityFile /root/.ssh/id_github
        EOF
        ssh-keyscan -t rsa github.com > /root/.ssh/known_hosts
    volumes:
      - name: ssh
        path: /root/.ssh

  - id: 'Clone env repository from github'
    name: gcr.io/cloud-builders/git
    args:
      - clone
      - --recurse-submodules
      - git@github.com:rafty/gcp-gke-gitops-env.git
    volumes:
      - name: ssh
        path: /root/.ssh
  ### - GitHub Env repo Access by SSH

  # dirを変更するのがポイント
  - id: 'Checkout production branch'
    name: gcr.io/cloud-builders/git
    dir: gcp-gke-gitops-env
    entrypoint: /bin/sh
    args:
      - -c
      - |
        set -x && \
        git config --global user.email $(git log --format='%an <%ae>' -n 1 HEAD | sed 's/.*\<\([^>]*\)\>.*/\1/g') && \
        git fetch origin production && git switch production && \
        git checkout $COMMIT_SHA kubernetes.yaml
    volumes:
      - name: ssh
        path: /root/.ssh

  - id: 'Copy file'
    name: gcr.io/cloud-builders/gcloud
    entrypoint: /bin/sh
    args:
      - -c
      - |
        set -x && \
        cp kubernetes.yaml gcp-gke-gitops-env/

  # dirを変更するのがポイント
  - id: 'Copy to production branch'
    name: gcr.io/cloud-builders/git
    dir: gcp-gke-gitops-env
    entrypoint: /bin/sh
    args:
      - -c
      - |
        set -x && \
        git commit \
        --author="Cloud Build Service Account <$(gcloud auth list --filter=status:ACTIVE --format='value(account)')>" \
        -m "Manifest from commit $COMMIT_SHA $(git log --format=%B -n 1 $COMMIT_SHA)" && \
        git push origin production
    volumes:
      - name: ssh
        path: /root/.ssh
